// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5UZCEV5-KpRSDYSoUt4l8dM9KG5k40ME',
    appId: '1:213014118413:web:ffc86e1981ba43da605544',
    messagingSenderId: '213014118413',
    projectId: 'yoman016-575a3',
    authDomain: 'yoman016-575a3.firebaseapp.com',
    storageBucket: 'yoman016-575a3.firebasestorage.app',
    measurementId: 'G-31RTT438RL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABQBYQ5EqUH4VoFDouVWC9-p5W_fDizzc',
    appId: '1:213014118413:android:c8658e954f8b4790605544',
    messagingSenderId: '213014118413',
    projectId: 'yoman016-575a3',
    storageBucket: 'yoman016-575a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-jjbmZSVW_bMJQllLWrBmFXv-ig30dkg',
    appId: '1:213014118413:ios:76b2952faa495f9d605544',
    messagingSenderId: '213014118413',
    projectId: 'yoman016-575a3',
    storageBucket: 'yoman016-575a3.firebasestorage.app',
    iosBundleId: 'com.yoman.yoberg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-jjbmZSVW_bMJQllLWrBmFXv-ig30dkg',
    appId: '1:213014118413:ios:76b2952faa495f9d605544',
    messagingSenderId: '213014118413',
    projectId: 'yoman016-575a3',
    storageBucket: 'yoman016-575a3.firebasestorage.app',
    iosBundleId: 'com.yoman.yoberg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5UZCEV5-KpRSDYSoUt4l8dM9KG5k40ME',
    appId: '1:213014118413:web:b58d8e87cdff1f1e605544',
    messagingSenderId: '213014118413',
    projectId: 'yoman016-575a3',
    authDomain: 'yoman016-575a3.firebaseapp.com',
    storageBucket: 'yoman016-575a3.firebasestorage.app',
    measurementId: 'G-SWMSZ2ECGJ',
  );
}
